services:
  dataspace_backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      MODULE_NAME: app.main
    env_file:
      - .env
    depends_on:
      - fuseki
      - timescaledb
      - mongodb

  fuseki:
    image: stain/jena-fuseki
    environment:
      ADMIN_PASSWORD: admin
      WEBSITES_ENABLE_APP_SERVICE_STORAGE: TRUE
    ports:
      - "3030:3030"
    # volumes:
    #   - ./fuseki_data:/fuseki

  timescaledb:
    image: timescale/timescaledb:latest-pg12
    environment:
      POSTGRES_DB: postgres_test
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "shared_preload_libraries=timescaledb", "-c", "log_statement=all"]
    # volumes:
    #   - ./init:/docker-entrypoint-initdb.d

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    # volumes:
    #   - ./mongo_data:/data/db